### ISSUE TITLE
Plugin does not compile

### ISSUE THREAD

**Issue by inesevira** [breakstring/AzureTTS#1]
Hi, 

When added to my UE 4.27 project into Plugins folder, it  says:
![image](https://user-images.githubusercontent.com/49145687/136026872-9b06dab7-6aac-4e46-bcd1-7cbb4057b2ad.png)
 when I rebuilding it, it says again: ... could not be compiled. Try rebuilding from the source manually.

Any suggestions?

Thanks.

**Comment by breakstring** [comment]
> Hi,
> 
> When added to my UE 4.27 project into Plugins folder, it says: ![image](https://user-images.githubusercontent.com/49145687/136026872-9b06dab7-6aac-4e46-bcd1-7cbb4057b2ad.png) when I rebuilding it, it says again: ... could not be compiled. Try rebuilding from the source manually.
> 
> Any suggestions?
> 
> Thanks.

I'm tried to created a new UE4.27 C++ project,  and put this repo under Plugins foler( struct as PROJECTROOT/Plugins/AzureTTS ). Then compiled it with Visual Studio 2019 & Rider, all these two IDEs can compile successe...

**Comment by inesevira** [comment]
Hi, 

Thank you for the answer :) Sorry I am not a coder. 

So, I created a new project and added files to Plugins folder, when trying to generate Visual Studio project files it says: 
![image](https://user-images.githubusercontent.com/49145687/136914159-2bb6aae9-006c-48cf-94d8-5b769471fbb0.png)

**Comment by inesevira** [comment]
Hi, Any help please? what would be the steps to do to compile the files? Thanks :)

**Comment by inesevira** [comment]
Ha! I think I got it :) thanks again!

**Comment by breakstring** [comment]
> Ha! I think I got it :) thanks again!

Sorry for miss this thread. Glad to know you reresolved this problem. :)
